### ISSUE TITLE
"remove_non_gsm_chars" method error

### ISSUE THREAD

**Issue by thisistouhid** [acpmasquerade/sms-counter-php#2]
Getting error: **Only variables should be passed by reference** when using `SMSCounter::remove_non_gsm_chars('This is a test');`

and Getting error: **Call-time pass-by-reference has been removed**
when using 
`$t='This is a test';`
`return (array) SMSCounter::remove_non_gsm_chars(&$t);`

**Comment by acpmasquerade** [comment]
But why are you passing by reference ? 

````php
$t = "This is a test';
$t_clean = SMSCounter::remove_non_gsm_chars($t);
````

Just do this.

**Comment by thisistouhid** [comment]
I am using it on laravel 4 and your code:
`$t = "This is a test';`
`$t_clean = SMSCounter::remove_non_gsm_chars($t);`
 produce this error:
`Only variables should be passed by reference`

**Comment by acpmasquerade** [comment]
Are you still having the issue ?

**Comment by thisistouhid** [comment]
![error](https://cloud.githubusercontent.com/assets/4920284/6727093/a4cb2784-ce48-11e4-8be3-52a6a9ddbc8e.png)

**Comment by acpmasquerade** [comment]
You are seeing the error because of the strict standards enabled on your installation / project. 

I will update the code such that it follows the strict standards. 

Thank You.
