### ISSUE TITLE
Detect encoding fails when using +

### ISSUE THREAD

**Issue by luishdez** [acpmasquerade/sms-counter-php#4]
The `+` symbol shouldn't count as an UTF16 symbol but it does.

```php
$info = \SMSCounter::count('Hello +This is message');
echo $info->enconding; // "UTF16"
```

It will be nice to add a test with the whole GSM charset …

**Comment by acpmasquerade** [comment]
Thank You @luishdez 
fixed and closed

**Comment by acpmasquerade** [comment]
@luishdez , 
Seems like this issue was what inspired you in refactoring and working on the sms counter library. Checked your code. Thank you for making it better. However, would have been happier if you have forked and taken ahead.

Readme updated mentioning your repo.

**Comment by luishdez** [comment]
@acpmasquerade Thanks we use this at www.instasent.com and we needed to add some extra functionality so forking was the best option.
