### ISSUE TITLE
Is Hypen also counted as Unicode?

### ISSUE THREAD

**Issue by pdctpa** [acpmasquerade/sms-counter-php#6]
Is Hyphen also counted as Unicode message, mine detecting as unicode when hypen (-) is used in the message content.

**Comment by acpmasquerade** [comment]
Hyphen is not counted as Unicode. You might have used some other hyphen like Unicode symbol. 
https://www.cs.tut.fi/~jkorpela/dashes.html

**Comment by acpmasquerade** [comment]
stdClass Object
(
    [encoding] => GSM_7BIT
    [length] => 1
    [per_message] => 160
    [remaining] => 159
    [messages] => 1
)

Expected output for an ASCII hyphen (-)

**Comment by pdctpa** [comment]
This is probably because I copy pasted from WEB. Is it?

**Comment by acpmasquerade** [comment]
that might be the case.
